### PR TITLE
Resolves #5, #2 and also supports UID only mapping

### LINKED ISSUE #5: Optional UID and GID
Currently the input arguments support optional GID and in that case UID is used as the GID as well.

It'd be nice if either of them can truly be optional and treat them as separate entity.

In the case of LXC GPU passthrough, we only need to map the `video` and `render` **groups** in host to container.

The mapping should look like the following:

```
lxc.idmap: u 0 100000 65536    // map UIDs 0-65535 (LXC namespace) to 100000-165535 (host namespace)
lxc.idmap: g 0 100000 44       // map GIDs 0-43 (LXC namspace) to 100000-100043 (host namespace)
lxc.idmap: g 44 44 1           // map GID  44 to be the same in both namespaces
lxc.idmap: g 45 100045 61      // map GIDs 45-105 (LXC namspace) to 100045-100105 (host namespace)
lxc.idmap: g 106 108 1         // map GID  106 (LXC namspace) to 108 (host namespace)
lxc.idmap: g 107 100107 65429  // map GIDs 107-65536 (LXC namspace) to 100107-165536 (host namespace)
```

But the closest output one can get currently is the following:

```
❯ ./run.py 44=44  106=108

# Add to /etc/pve/lxc/<container_id>.conf:
lxc.idmap: u 0 100000 44
lxc.idmap: g 0 100000 44
lxc.idmap: u 44 44 1
lxc.idmap: g 44 44 1
lxc.idmap: u 45 100045 61
lxc.idmap: g 45 100045 61
lxc.idmap: u 106 108 1
lxc.idmap: g 106 108 1
lxc.idmap: u 107 100107 65429
lxc.idmap: g 107 100107 65429

# Add to /etc/subuid:
root:44:1
root:108:1

# Add to /etc/subgid:
root:44:1
root:108:1
```

### PR DESCRIPTION
**Pull request by mnestor**
# only map GID
./run.py :100=:100

### CODE REVIEW

**Comment by mnestor** [comment]
Also included a fix for #2 I believe. Still not 100% certain of idmaps so tell me if I'm wrong here

```
root@pve1:~# ./idmap.py 1037:100 :44 :108 1896 1897 1898

# Add to /etc/pve/lxc/<container_id>.conf:
lxc.idmap: u 0 100000 1037
lxc.idmap: u 1037 1037 1
lxc.idmap: u 1038 101038 858
lxc.idmap: u 1896 1896 1
lxc.idmap: u 1897 1897 1
lxc.idmap: u 1898 1898 1
lxc.idmap: u 1899 101899 63637
lxc.idmap: g 0 100000 44
lxc.idmap: g 44 44 1
lxc.idmap: g 45 100045 55
lxc.idmap: g 100 100 1
lxc.idmap: g 101 100101 7
lxc.idmap: g 108 108 1
lxc.idmap: g 109 100109 1787
lxc.idmap: g 1896 1896 1
lxc.idmap: g 1897 1897 1
lxc.idmap: g 1898 1898 1
lxc.idmap: g 1899 101899 63637

# Add to /etc/subuid:
root:1037:1
root:1896:1
root:1897:1
root:1898:1

# Add to /etc/subgid:
root:44:1
root:100:1
root:108:1
root:1896:1
root:1897:1
root:1898:1
```

**Comment by mnestor** [comment]
And the final with UID only mapping as well

```
root@pve1:~# ./idmap.py 1037:100 :44 :108 1896 1897: 1898:=9990:

# Add to /etc/pve/lxc/<container_id>.conf:
lxc.idmap: u 0 100000 1037
lxc.idmap: u 1037 1037 1
lxc.idmap: u 1038 101038 858
lxc.idmap: u 1896 1896 1
lxc.idmap: u 1897 1897 1
lxc.idmap: u 1898 9990 1
lxc.idmap: u 1899 101899 63637
lxc.idmap: g 0 100000 44
lxc.idmap: g 44 44 1
lxc.idmap: g 45 100045 55
lxc.idmap: g 100 100 1
lxc.idmap: g 101 100101 7
lxc.idmap: g 108 108 1
lxc.idmap: g 109 100109 1787
lxc.idmap: g 1896 1896 1
lxc.idmap: g 1897 101897 63639

# Add to /etc/subuid:
root:1037:1
root:1896:1
root:1897:1
root:9990:1

# Add to /etc/subgid:
root:44:1
root:100:1
root:108:1
root:1896:1
```

**Comment by taai** [comment]
Hey, @mnestor !
Your code works for me, but only when ```root:100000:65536``` is added in both ```/etc/subuid``` and ```/etc/subgid``` files.
Thank you! 👍

**Comment by ddimick** [comment]
Thank you for the patch!

**Pull request merged**
